export function generatePDFFromPopup() {
    const {jsPDF} = window.jspdf || {};
    if (!jsPDF) {
        console.error("jsPDF not loaded.");
        return;
    }

    chrome.tabs.query({active: true, currentWindow: true}, (tabs) => {
        if (!tabs[0]?.id) return;

        chrome.tabs.sendMessage(tabs[0].id, {type: "GET_NUMBER_PLATE"}, (response) => {
            const numberPlate = response?.numberPlate || "Unknown Plate";
            const doc = new jsPDF({unit: "mm", format: "a4"});

            let y = 20;
            const pageWidth = doc.internal.pageSize.getWidth();
            const margin = 15;
            const labelWidth = 60;
            const valueStart = margin + labelWidth + 5;
            const lineHeight = 8;
            const sectionGap = 10;

            const headingHeight = 8;
            const headingBgColor = [63, 81, 181]; // Indigo (RGB)
            const headingTextColor = [255, 255, 255]; // White

            const drawSectionTitle = (title) => {
                // Draw background rectangle
                doc.setFillColor(...headingBgColor);
                doc.rect(margin, y, pageWidth - margin * 2, headingHeight, 'F');

                // Draw text on top
                doc.setFont("helvetica", "bold");
                doc.setTextColor(...headingTextColor);
                doc.setFontSize(12);
                doc.text(title, margin + 2, y + 5.5);

                // Reset text color for next content
                doc.setTextColor(0, 0, 0);
                y += headingHeight + 4;
                //     adding  bottom margin after indigo section
                y += sectionGap;

            };

            const drawField = (label, value) => {
                doc.setFont("helvetica", "normal");
                doc.setFontSize(11);
                doc.text(`${label}:`, margin, y);
                doc.setFont("helvetica", "bold");
                doc.text(`${value}`, valueStart, y);
                y += lineHeight;
            };

            // Title
            doc.setFont("helvetica", "bold");
            doc.setFontSize(16);
            doc.text("Vehicle Profit Report", margin, y);
            y += 10;

            // Vehicle Info Section
            drawSectionTitle("Vehicle Details");
            drawField("Vehicle Registration", numberPlate);
            y += sectionGap;

            // Deal Summary Section
            drawSectionTitle("Deal Summary");

            const retail = document.getElementById("retail").value;
            const position = document.getElementById("position").value;
            const marginVal = document.getElementById("margin").value;
            const costs = document.getElementById("costs").value;
            const result = document.getElementById("result").value;

            drawField("Retail Price", ` ${retail}`);
            drawField("Price Position (%)", `${position}%`);
            drawField("Costs", ` ${costs}`);
            drawField("Max Purchase Price", ` ${result}`);
            drawField("Chassis Margin Target", ` ${marginVal}`);
            y += sectionGap;

            // Finance Commission Section
            drawSectionTitle("Finance Commission");

            const commissionRate = document.getElementById("commissionRate").value;
            const commission = document.getElementById("commission").value;
            const totalMargin = document.getElementById("totalMargin").value;

            drawField("Commission Rate (%)", `${commissionRate}%`);
            drawField("Finance Commission", ` ${commission}`);
            drawField("Total Potential Margin", ` ${totalMargin}`);

            // Footer
            y = doc.internal.pageSize.getHeight() - 20;
            doc.setFont("helvetica", "italic");
            doc.setFontSize(10);
            // doc.text("Generated by BCA Retail Price Calculator", margin, y);

            const filename = `${numberPlate}.pdf`;
            doc.save(filename);
        });
    });
}
